services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - jenkins
      - web-backend
    networks:
      - jenkins-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_config:/var/jenkins_home/init.groovy.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_PASS=${JENKINS_PASS:-admin123}
      - JENKINS_ENABLE_HYBRID_AUTH=true
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - COGNITO_DOMAIN=${COGNITO_DOMAIN}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    user: root
    networks:
      - jenkins-network

  web-backend:
    build: ./backend
    container_name: web-backend
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - ./web:/app/web:ro
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER=${JENKINS_USER:-admin}
      - JENKINS_PASS=${JENKINS_PASS:-admin123}
      - COGNITO_DOMAIN=${COGNITO_DOMAIN}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_WEB_CLIENT_ID=${COGNITO_WEB_CLIENT_ID}
      - SLACK_WEBHOOK_TOKEN=${SLACK_WEBHOOK_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
    networks:
      - jenkins-network
    depends_on:
      - jenkins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-network:
    driver: bridge